"""empty message

Revision ID: 202104ceab05
Revises: 
Create Date: 2018-06-16 16:50:38.680129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202104ceab05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
