"""empty message

Revision ID: 23f31bac0d7f
Revises: a8583e507df7
Create Date: 2018-06-21 17:02:51.225418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f31bac0d7f'
down_revision = 'a8583e507df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_table_password', table_name='user_table')
    op.create_index(op.f('ix_user_table_password'), 'user_table', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_password'), table_name='user_table')
    op.create_index('ix_user_table_password', 'user_table', ['password'], unique=True)
    # ### end Alembic commands ###
