"""empty message

Revision ID: 89a61fa29a93
Revises: 31888642621b
Create Date: 2018-07-01 17:02:54.275275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a61fa29a93'
down_revision = '31888642621b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_table', sa.Column('chat_contents', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_table', 'chat_contents')
    # ### end Alembic commands ###
