"""empty message

Revision ID: a8583e507df7
Revises: 164489c694f2
Create Date: 2018-06-20 22:49:27.544002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8583e507df7'
down_revision = '164489c694f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('password', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_user_table_password'), 'user_table', ['password'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_password'), table_name='user_table')
    op.drop_column('user_table', 'password')
    # ### end Alembic commands ###
