"""empty message

Revision ID: e1adc6885ee7
Revises: 23f31bac0d7f
Create Date: 2018-06-22 07:27:42.972007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1adc6885ee7'
down_revision = '23f31bac0d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_table', sa.Column('filepath1', sa.String(length=100), nullable=True))
    op.add_column('goods_table', sa.Column('filepath2', sa.String(length=100), nullable=True))
    op.add_column('goods_table', sa.Column('filepath3', sa.String(length=100), nullable=True))
    op.drop_column('goods_table', 'filepath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_table', sa.Column('filepath', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('goods_table', 'filepath3')
    op.drop_column('goods_table', 'filepath2')
    op.drop_column('goods_table', 'filepath1')
    # ### end Alembic commands ###
